spring.application.name=WSRest-M2

# Enable the H2 web console for browser access
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
# Default username and password (H2 default username is 'sa', no password by default)
spring.datasource.username=sa
spring.datasource.password=sa

# JPA / Hibernate Configuration
# 'create-drop' est nécessaire pour que import.sql s'exécute à chaque démarrage
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Script Initialization
# defer-datasource-initialization=true assure que Hibernate crée les tables AVANT d'exécuter import.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Database URL
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# App Secrets
key-hash=eyJhbGciOiJIUzI1NiJ9.e30.6RWK2WeABTbTbdj_HScfUexOQ3J4_6wNc5N3WR-AE0w
minutes-expired=120

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
