spring.application.name=WSRest-M2

# Enable the H2 web console for browser access
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
# Default username and password (H2 default username is 'sa', no password by default)
spring.datasource.username=sa
spring.datasource.password=sa
# Configure JPA/Hibernate settings (optional)
spring.jpa.hibernate.ddl-auto=update
# Ensure the database stays open when connections close (useful during development)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
key-hash=eyJhbGciOiJIUzI1NiJ9.e30.6RWK2WeABTbTbdj_HScfUexOQ3J4_6wNc5N3WR-AE0w
minutes-expired=120
